name: VideoLive
options:
  bundleIdPrefix: com.sendbird.live
  deploymentTarget:
    iOS: "14.0"
  xcodeVersion: "15.0"
  developmentLanguage: en
  defaultConfig: Release

configs:
  Debug: debug
  Release: release

settings:
  base:
    DEVELOPMENT_TEAM: RM4A5PXTUX
    CLANG_CXX_LANGUAGE_STANDARD: gnu++20
    GCC_C_LANGUAGE_STANDARD: gnu11
  configs:
    Debug:
      DEBUG_INFORMATION_FORMAT: dwarf
      ENABLE_TESTABILITY: YES
      GCC_OPTIMIZATION_LEVEL: 0
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      GCC_PREPROCESSOR_DEFINITIONS:
        - DEBUG=1
        - $(inherited)
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      ONLY_ACTIVE_ARCH: YES
    Release:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      ENABLE_NS_ASSERTIONS: NO
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      VALIDATE_PRODUCT: YES
      MTL_ENABLE_DEBUG_INFO: NO

packages:
  SendbirdLiveSDK:
    url: https://github.com/sendbird/sendbird-live-sdk-ios
    from: "1.5.0"
  SendbirdUIKit:
    url: https://github.com/sendbird/sendbird-uikit-ios
    from: "3.32.0"

targets:
  VideoLive:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: VideoLive
        excludes:
          - "**/*.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sendbird.live.MultiHost
        INFOPLIST_FILE: VideoLive/Info.plist
        CODE_SIGN_ENTITLEMENTS: VideoLive/VideoLive.entitlements
        CODE_SIGN_IDENTITY: Apple Development
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1
        CURRENT_PROJECT_VERSION: 14
        MARKETING_VERSION: "1.0"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSCameraUsageDescription: "Please allow camera usage"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Please allow microphone usage"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Please allow photo library usage"
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        INFOPLIST_KEY_UIMainStoryboardFile: Main
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/Frameworks"
    dependencies:
      - package: SendbirdLiveSDK
      - package: SendbirdUIKit

schemes:
  VideoLive:
    build:
      targets:
        VideoLive: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
